openapi: 3.0.0
info:
  version: 1.0.0
  title: Test spec for OpenAPI3RouterFactoryTest
  license:
    name: Apache 2.0 License
paths:
  /example:
    get:
      summary: Example
      operationId: example
      responses:
        200:
          description: Empty json
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Example"

components:
  schemas:
    Example:
      type: object
      additionalProperties: true